create extension if not exists pgcrypto;
create table if not exists public.markets (id uuid primary key default gen_random_uuid(), symbol text not null unique, name text not null, region text not null, category text not null default 'Index', current_value numeric(18,4), change_value numeric(18,4), change_percent numeric(10,4), open_value numeric(18,4), high_value numeric(18,4), low_value numeric(18,4), previous_close numeric(18,4), week_52_high numeric(18,4), week_52_low numeric(18,4), currency text not null default 'USD', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.market_history (id uuid primary key default gen_random_uuid(), market_id uuid not null references public.markets(id) on delete cascade, timestamp timestamptz not null, value numeric(18,4) not null, volume numeric(20,2), created_at timestamptz not null default now());
create index if not exists market_history_market_id_idx on public.market_history(market_id); create index if not exists market_history_timestamp_idx on public.market_history(timestamp); create unique index if not exists market_history_market_timestamp_key on public.market_history(market_id, timestamp);
create table if not exists public.research_articles (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, subtitle text, excerpt text not null, category text not null, author text, published_at timestamptz, reading_time text, featured boolean not null default false, cover_image text, body_html text not null default '', blocks jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.research_articles add column if not exists body_html text not null default '';
create table if not exists public.research_sources (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.research_articles(id) on delete cascade, title text not null, url text not null, source_type text, created_at timestamptz not null default now());
alter table public.markets enable row level security; alter table public.market_history enable row level security; alter table public.research_articles enable row level security; alter table public.research_sources enable row level security;
create policy "Public can read active markets" on public.markets for select using (is_active); create policy "Public can read market history" on public.market_history for select using (true); create policy "Public can read published research" on public.research_articles for select using (published_at <= now()); create policy "Public can read research sources" on public.research_sources for select using (true);
